export const DEFAULT_NO_BRO_SERVER_PORT = 45678;
export const DEFAULT_NO_BRO_WORKERS_COUNT = 10;
export const DEFAULT_NO_BRO_STORE_RESPONSE_MS = 60000;

export const DEFAULT_QUEUE_TICK_EVENT_NAME = 'tick';
